version: "2"

linters:
  default: all
  disable:
    - ireturn
    - wrapcheck
    - wsl
    - depguard
    - exhaustruct
    - noinlineerr
  exclusions:
    rules:
      - text: "TODO"
        linters:
          - godox
  settings:
    revive:
      rules:
        - name: exported
          disabled: true