version: '3'

tasks:
  lint:
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.4.0
      - golangci-lint run --fix --config .golangci.yml --show-stats --color "always" -j {{.THREADS}}
    vars:
      THREADS:
        sh: nproc
  test:
    cmds:
      - go install gotest.tools/gotestsum@latest
      - gotestsum --format testname -- -covermode=atomic -failfast -timeout 5m ./...
    env:
        GOMAXPROCS: 4